### ISSUE TITLE
Constraints on the "WorkParameters" interface

### ISSUE THREAD

**Issue by nedtwigg** [gradle-guides/using-the-worker-api#10]
What [the guide says](https://guides.gradle.org/using-the-worker-api/#converting_to_the_worker_api):

- Use `Property` objects to represent the source and MD5 hash files.

What I found to be true after some trial and error:

- Every method in the interface needs to start with `get`
- Every method in the interface needs to return an `org.gradle.api.provider.Property`

If you don't do all of the above, then you will get errors like:

```
> Could not create an instance of type com.diffplug.gradle.imagegrinder.ImageGrinderTask$Params.
  > Could not generate a decorated class for interface com.diffplug.gradle.imagegrinder.ImageGrinderTask$Params.
    > Cannot have abstract method Params.taskRef().
```

It would help if:

- the documentation clearly stated that every method should be a `getXXX()`
- the error message suggested "maybe the interface should be `getXXX()` instead of `XXX()".

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #295](https://github.com/gradle/guides/issues/295) via [**ZenHub**](https://www.zenhub.com/)
