### ISSUE TITLE
Clarify advantage of intra-project parallelism 

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/using-the-worker-api#3]
We currently start the guide with:

> The Worker API provides the ability to break up the execution of a task action into discrete units of work and then to execute that work concurrently and asynchronously.

It imples what can be summarized with the feedback we received:

> The purpose of Worker API seems to be to parallelize a single task and make it leverage multiple threads, which is good for making a single task faster.

What worker API very importantly also provides is safe parallelism of tasks within a single project. Let's make sure we make this point clearly at the beginning of the guide.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #282](https://github.com/gradle/guides/issues/282) via [**ZenHub**](https://www.zenhub.com/)
